/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVencimentosRouteImport } from './routes/_authenticated/vencimentos'
import { Route as AuthenticatedVeiculosRouteImport } from './routes/_authenticated/veiculos'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedMotoristasRouteImport } from './routes/_authenticated/motoristas'
import { Route as AuthenticatedManutencoesRouteImport } from './routes/_authenticated/manutencoes'
import { Route as AuthenticatedCustosRouteImport } from './routes/_authenticated/custos'
import { Route as AuthenticatedBuscaRouteImport } from './routes/_authenticated/busca'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVencimentosRoute =
  AuthenticatedVencimentosRouteImport.update({
    id: '/vencimentos',
    path: '/vencimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVeiculosRoute = AuthenticatedVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotoristasRoute = AuthenticatedMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManutencoesRoute =
  AuthenticatedManutencoesRouteImport.update({
    id: '/manutencoes',
    path: '/manutencoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustosRoute = AuthenticatedCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuscaRoute = AuthenticatedBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/manutencoes': typeof AuthenticatedManutencoesRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/vencimentos': typeof AuthenticatedVencimentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/manutencoes': typeof AuthenticatedManutencoesRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/vencimentos': typeof AuthenticatedVencimentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/busca': typeof AuthenticatedBuscaRoute
  '/_authenticated/custos': typeof AuthenticatedCustosRoute
  '/_authenticated/manutencoes': typeof AuthenticatedManutencoesRoute
  '/_authenticated/motoristas': typeof AuthenticatedMotoristasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/veiculos': typeof AuthenticatedVeiculosRoute
  '/_authenticated/vencimentos': typeof AuthenticatedVencimentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/avisos'
    | '/busca'
    | '/custos'
    | '/manutencoes'
    | '/motoristas'
    | '/painel'
    | '/relatorios'
    | '/usuarios'
    | '/veiculos'
    | '/vencimentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/avisos'
    | '/busca'
    | '/custos'
    | '/manutencoes'
    | '/motoristas'
    | '/painel'
    | '/relatorios'
    | '/usuarios'
    | '/veiculos'
    | '/vencimentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/avisos'
    | '/_authenticated/busca'
    | '/_authenticated/custos'
    | '/_authenticated/manutencoes'
    | '/_authenticated/motoristas'
    | '/_authenticated/painel'
    | '/_authenticated/relatorios'
    | '/_authenticated/usuarios'
    | '/_authenticated/veiculos'
    | '/_authenticated/vencimentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vencimentos': {
      id: '/_authenticated/vencimentos'
      path: '/vencimentos'
      fullPath: '/vencimentos'
      preLoaderRoute: typeof AuthenticatedVencimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculos': {
      id: '/_authenticated/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedVeiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motoristas': {
      id: '/_authenticated/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof AuthenticatedMotoristasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencoes': {
      id: '/_authenticated/manutencoes'
      path: '/manutencoes'
      fullPath: '/manutencoes'
      preLoaderRoute: typeof AuthenticatedManutencoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custos': {
      id: '/_authenticated/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof AuthenticatedCustosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/busca': {
      id: '/_authenticated/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof AuthenticatedBuscaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedBuscaRoute: typeof AuthenticatedBuscaRoute
  AuthenticatedCustosRoute: typeof AuthenticatedCustosRoute
  AuthenticatedManutencoesRoute: typeof AuthenticatedManutencoesRoute
  AuthenticatedMotoristasRoute: typeof AuthenticatedMotoristasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVeiculosRoute: typeof AuthenticatedVeiculosRoute
  AuthenticatedVencimentosRoute: typeof AuthenticatedVencimentosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedBuscaRoute: AuthenticatedBuscaRoute,
  AuthenticatedCustosRoute: AuthenticatedCustosRoute,
  AuthenticatedManutencoesRoute: AuthenticatedManutencoesRoute,
  AuthenticatedMotoristasRoute: AuthenticatedMotoristasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVeiculosRoute: AuthenticatedVeiculosRoute,
  AuthenticatedVencimentosRoute: AuthenticatedVencimentosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
