ALTER TABLE public.veiculos
  ADD COLUMN IF NOT EXISTS codigo TEXT,
  ADD COLUMN IF NOT EXISTS tipo TEXT,
  ADD COLUMN IF NOT EXISTS cor TEXT,
  ADD COLUMN IF NOT EXISTS departamento TEXT,
  ADD COLUMN IF NOT EXISTS fotos TEXT[] NOT NULL DEFAULT '{}';

ALTER TABLE public.veiculos ALTER COLUMN nome DROP NOT NULL;
ALTER TABLE public.veiculos DROP CONSTRAINT IF EXISTS veiculos_placa_key;